import io
from typing import Optional, List, Dict, Any, Tuple
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.schemas.document import ExportRequest


class ExportService:
    """
    Generates downloadable reports in TXT, Markdown, PDF, and DOCX formats.
    """

    @classmethod
    def generate_export_bytes(cls, req: ExportRequest) -> Tuple[bytes, str, str]:
        fmt = req.format.lower().strip()
        if fmt == "markdown" or fmt == "md":
            return cls._export_markdown(req), "text/markdown", f"{req.filename}.md"
        elif fmt == "pdf":
            return cls._export_pdf(req), "application/pdf", f"{req.filename}.pdf"
        elif fmt == "docx":
            return cls._export_docx(req), "application/vnd.openxmlformats-officedocument.wordprocessingml.document", f"{req.filename}.docx"
        else:
            return cls._export_txt(req), "text/plain", f"{req.filename}.txt"

    @classmethod
    def _export_txt(cls, req: ExportRequest) -> bytes:
        lines = [
            f"==================================================",
            f" {req.title.upper()} ",
            f"==================================================",
            "",
            "--- AI GENERATED SUMMARY ---",
            req.summary,
            ""
        ]

        if req.simplified_summary:
            lines.extend([
                "--- SIMPLIFIED EXPLANATION ---",
                req.simplified_summary,
                ""
            ])

        if req.key_points:
            lines.extend([
                "--- KEY POINTS & INSIGHTS ---",
                *[f"• {kp}" for kp in req.key_points],
                ""
            ])

        if req.keywords:
            lines.extend([
                "--- KEYWORDS ---",
                ", ".join(req.keywords),
                ""
            ])

        if req.topics:
            lines.extend([
                "--- TOPICS ---",
                ", ".join(req.topics),
                ""
            ])

        if req.stats:
            lines.extend([
                "--- DOCUMENT STATISTICS ---",
                *[f"{k.replace('_', ' ').title()}: {v}" for k, v in req.stats.items()],
                ""
            ])

        return "\n".join(lines).encode("utf-8")

    @classmethod
    def _export_markdown(cls, req: ExportRequest) -> bytes:
        lines = [
            f"# {req.title}",
            "",
            "> *Generated by ContextAI (AI Text Reader, Analyzer & Summarizer)*",
            "",
            "## 📄 AI Summary",
            req.summary,
            ""
        ]

        if req.simplified_summary:
            lines.extend([
                "## 💡 Simplified Explanation",
                req.simplified_summary,
                ""
            ])

        if req.key_points:
            lines.extend([
                "## 🎯 Key Points & Insights",
                *[f"- **{kp}**" if ":" in kp else f"- {kp}" for kp in req.key_points],
                ""
            ])

        if req.keywords:
            lines.extend([
                "## 🏷️ Keywords",
                " ".join([f"`{kw}`" for kw in req.keywords]),
                ""
            ])

        if req.topics:
            lines.extend([
                "## 🌐 Detected Topics",
                *[f"- {top}" for top in req.topics],
                ""
            ])

        if req.stats:
            lines.extend([
                "## 📊 Document Metrics",
                "| Metric | Value |",
                "|---|---|",
                *[f"| {k.replace('_', ' ').title()} | {v} |" for k, v in req.stats.items()],
                ""
            ])

        return "\n".join(lines).encode("utf-8")

    @classmethod
    def _export_docx(cls, req: ExportRequest) -> bytes:
        doc = docx.Document()

        # Title
        title_p = doc.add_paragraph()
        title_p.paragraph_format.space_before = Pt(0)
        title_p.paragraph_format.space_after = Pt(12)
        run = title_p.add_run(req.title)
        run.font.size = Pt(22)
        run.font.bold = True
        run.font.color.rgb = RGBColor(30, 58, 138)

        # Subtitle
        sub_p = doc.add_paragraph()
        sub_run = sub_p.add_run("Generated by ContextAI Document Intelligence Assistant")
        sub_run.font.size = Pt(10)
        sub_run.font.italic = True
        sub_run.font.color.rgb = RGBColor(100, 116, 139)

        # Summary Section
        h1 = doc.add_heading("AI Summary", level=1)
        h1.style.font.color.rgb = RGBColor(30, 58, 138)
        for para_text in req.summary.split("\n\n"):
            if para_text.strip():
                p = doc.add_paragraph(para_text.strip())
                p.paragraph_format.line_spacing = 1.15

        if req.simplified_summary:
            doc.add_heading("Simplified Explanation", level=1)
            doc.add_paragraph(req.simplified_summary)

        if req.key_points:
            doc.add_heading("Key Points & Takeaways", level=1)
            for kp in req.key_points:
                doc.add_paragraph(kp, style="List Bullet")

        if req.keywords:
            doc.add_heading("Keywords", level=1)
            doc.add_paragraph(", ".join(req.keywords))

        if req.stats:
            doc.add_heading("Document Metrics", level=1)
            table = doc.add_table(rows=1, cols=2)
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = "Metric"
            hdr_cells[1].text = "Value"
            for k, v in req.stats.items():
                row_cells = table.add_row().cells
                row_cells[0].text = str(k).replace("_", " ").title()
                row_cells[1].text = str(v)

        file_stream = io.BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)
        return file_stream.read()

    @classmethod
    def _export_pdf(cls, req: ExportRequest) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=45,
            leftMargin=45,
            topMargin=45,
            bottomMargin=45
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#1e3a8a"),
            spaceAfter=6
        )
        subtitle_style = ParagraphStyle(
            "DocSubtitle",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=14
        )
        h2_style = ParagraphStyle(
            "DocH2",
            parent=styles["Heading2"],
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#0f172a"),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
            spaceAfter=8
        )
        bullet_style = ParagraphStyle(
            "DocBullet",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1e293b"),
            leftIndent=15,
            spaceAfter=4
        )

        story = [
            Paragraph(req.title, title_style),
            Paragraph("Generated by ContextAI Document Intelligence Assistant", subtitle_style),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=12),
            Paragraph("AI Summary", h2_style)
        ]

        # Escape XML entities for ReportLab Paragraphs
        for p in req.summary.split("\n\n"):
            if p.strip():
                clean_p = p.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(clean_p, body_style))

        if req.simplified_summary:
            story.append(Spacer(1, 8))
            story.append(Paragraph("Simplified Explanation", h2_style))
            clean_sim = req.simplified_summary.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(clean_sim, body_style))

        if req.key_points:
            story.append(Spacer(1, 8))
            story.append(Paragraph("Key Points & Takeaways", h2_style))
            for kp in req.key_points:
                clean_kp = kp.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(f"&bull; {clean_kp}", bullet_style))

        if req.keywords:
            story.append(Spacer(1, 8))
            story.append(Paragraph("Key Terminology", h2_style))
            kw_str = ", ".join(req.keywords).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(kw_str, body_style))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()


Tuple_Bytes_Mime = tuple[bytes, str, str]
